// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://legcwttscdnlmghqqbog.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxlZ2N3dHRzY2RubG1naHFxYm9nIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAwOTUwMzUsImV4cCI6MjA1NTY3MTAzNX0.oJuA-2UpNyTjXbyMg08eN6c0CfuUFDefkWLSYOmByZY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);